import { LLMNodeData, LLMProvider } from "../types/nodes";
import { ApiKeys } from "../store/useSettingsStore";

export interface LLMRequestParams {
  provider: LLMProvider;
  model: string;
  systemPrompt?: string;
  userPrompt: string;
  temperature?: number;
  maxTokens?: number;
  jsonMode?: boolean;
  apiKeys: ApiKeys;
  mockMode?: boolean;
}

export interface LLMResponse {
  text: string;
  data?: any;
  tokensUsed: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
  durationMs: number;
  providerUsed: string;
}

// Simulated intelligent mock responses when in Mock / Sandbox mode
function generateMockResponse(params: LLMRequestParams): string {
  const { userPrompt, systemPrompt, jsonMode, model } = params;
  const promptLower = (userPrompt + " " + (systemPrompt || "")).toLowerCase();

  if (jsonMode) {
    if (promptLower.includes("sentiment") || promptLower.includes("triage") || promptLower.includes("support")) {
      return JSON.stringify(
        {
          sentiment: promptLower.includes("angry") || promptLower.includes("broken") || promptLower.includes("fail") ? "negative" : "positive",
          urgency: promptLower.includes("urgent") || promptLower.includes("asap") || promptLower.includes("critical") ? "high" : "medium",
          category: promptLower.includes("billing") ? "billing" : promptLower.includes("bug") ? "technical" : "general_inquiry",
          confidenceScore: 0.94,
          summary: "Customer inquiry processed and classified accurately by AI reasoning agent.",
          suggestedActions: [
            "Escalate to tier-2 support team",
            "Send priority acknowledgement email",
            "Create Jira tracking ticket"
          ]
        },
        null,
        2
      );
    }

    if (promptLower.includes("extract") || promptLower.includes("entities") || promptLower.includes("summary")) {
      return JSON.stringify(
        {
          keyInsights: [
            "High user interest in automated workflow orchestration",
            "Identified potential latency bottlenecks in synchronous API chaining",
            "Recommended caching intermediate transform layers"
          ],
          entities: [
            { name: "Workflow DAG", type: "architecture" },
            { name: "Latency SLA", type: "metric", value: "< 500ms" }
          ],
          status: "completed"
        },
        null,
        2
      );
    }

    return JSON.stringify(
      {
        result: "Processed successfully",
        model: model,
        timestamp: new Date().toISOString(),
        extractedPayload: {
          sampleOutput: "Simulated structured response for prompt: " + userPrompt.slice(0, 50) + "..."
        }
      },
      null,
      2
    );
  }

  // Non-JSON realistic markdown output
  if (promptLower.includes("summarize") || promptLower.includes("synthesis") || promptLower.includes("action item")) {
    return `### 📋 Executive Summary & Analysis\n\nBased on the workflow context and input data, here is the synthesized breakdown:\n\n1. **Core Findings:** The pipeline executed upstream operations successfully with zero dropped packets.\n2. **Action Items:**\n   - [x] Verify API payload contracts with external endpoints\n   - [ ] Implement retry backoff for rate-limited endpoints\n   - [ ] Archive execution logs to analytics store\n\n*Generated by ${model} simulation engine.*`;
  }

  if (promptLower.includes("code") || promptLower.includes("test") || promptLower.includes("function")) {
    return `\`\`\`typescript\n// Generated Test Suite for upstream code\nimport { describe, it, expect } from 'vitest';\n\ndescribe('Workflow Engine Pipeline', () => {\n  it('should transform incoming data and resolve templated tokens', async () => {\n    const result = await processPipelinePayload(${JSON.stringify({ testInput: "mock_data" })});\n    expect(result.status).toBe('success');\n    expect(result.data).toBeDefined();\n  });\n});\n\`\`\``;
  }

  return `**AI Agent Analysis (${model})**\n\nI have evaluated the provided input:\n\n> "${userPrompt.slice(0, 120)}${userPrompt.length > 120 ? "..." : ""}"\n\n**Output:**\nThe automated evaluation completed with optimal scores across reliability, format compliance, and semantic relevance. Ready for downstream transformation.`;
}

export async function executeLLMRequest(params: LLMRequestParams): Promise<LLMResponse> {
  const startTime = Date.now();

  // If mockMode is explicitly true, or provider is mock, or no API key is set for provider
  if (params.mockMode || params.provider === "mock") {
    // Simulate network latency (350ms - 800ms)
    await new Promise((resolve) => setTimeout(resolve, 400 + Math.random() * 400));

    const text = generateMockResponse(params);
    let parsedData: any = undefined;
    if (params.jsonMode) {
      try {
        parsedData = JSON.parse(text);
      } catch {
        // keep text
      }
    }

    const estimatedPromptTokens = Math.ceil((params.userPrompt.length + (params.systemPrompt?.length || 0)) / 4);
    const estimatedCompletionTokens = Math.ceil(text.length / 4);

    return {
      text,
      data: parsedData,
      tokensUsed: {
        promptTokens: estimatedPromptTokens,
        completionTokens: estimatedCompletionTokens,
        totalTokens: estimatedPromptTokens + estimatedCompletionTokens,
      },
      durationMs: Date.now() - startTime,
      providerUsed: `mock (${params.model})`,
    };
  }

  // --- Real Provider Integrations ---
  const { provider, model, systemPrompt, userPrompt, temperature = 0.7, maxTokens = 1024, jsonMode, apiKeys } = params;

  try {
    switch (provider) {
      case "openai": {
        const apiKey = apiKeys.openai;
        if (!apiKey) throw new Error("OpenAI API key is missing in Settings");

        const messages: any[] = [];
        if (systemPrompt) {
          messages.push({ role: "system", content: systemPrompt });
        }
        messages.push({ role: "user", content: userPrompt });

        const res = await fetch("https://api.openai.com/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model: model || "gpt-4o",
            messages,
            temperature,
            max_tokens: maxTokens,
            ...(jsonMode ? { response_format: { type: "json_object" } } : {}),
          }),
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData?.error?.message || `OpenAI error: ${res.statusText}`);
        }

        const data = await res.json();
        const text = data.choices?.[0]?.message?.content || "";
        let parsedData: any = undefined;
        if (jsonMode) {
          try {
            parsedData = JSON.parse(text);
          } catch {}
        }

        return {
          text,
          data: parsedData,
          tokensUsed: {
            promptTokens: data.usage?.prompt_tokens || 0,
            completionTokens: data.usage?.completion_tokens || 0,
            totalTokens: data.usage?.total_tokens || 0,
          },
          durationMs: Date.now() - startTime,
          providerUsed: `OpenAI (${model})`,
        };
      }

      case "anthropic": {
        const apiKey = apiKeys.anthropic;
        if (!apiKey) throw new Error("Anthropic Claude API key is missing in Settings");

        const res = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-api-key": apiKey,
            "anthropic-version": "2023-06-01",
            "anthropic-dangerous-direct-browser-access": "true",
          },
          body: JSON.stringify({
            model: model || "claude-3-5-sonnet-20241022",
            max_tokens: maxTokens,
            temperature,
            system: systemPrompt || undefined,
            messages: [{ role: "user", content: userPrompt }],
          }),
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData?.error?.message || `Anthropic error: ${res.statusText}`);
        }

        const data = await res.json();
        const text = data.content?.[0]?.text || "";
        let parsedData: any = undefined;
        if (jsonMode) {
          try {
            parsedData = JSON.parse(text);
          } catch {}
        }

        return {
          text,
          data: parsedData,
          tokensUsed: {
            promptTokens: data.usage?.input_tokens || 0,
            completionTokens: data.usage?.output_tokens || 0,
            totalTokens: (data.usage?.input_tokens || 0) + (data.usage?.output_tokens || 0),
          },
          durationMs: Date.now() - startTime,
          providerUsed: `Anthropic (${model})`,
        };
      }

      case "gemini": {
        const apiKey = apiKeys.gemini;
        if (!apiKey) throw new Error("Google Gemini API key is missing in Settings");

        const geminiModel = model.includes("gemini") ? model : "gemini-1.5-flash";
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${geminiModel}:generateContent?key=${apiKey}`;

        const contents: any[] = [];
        const parts: any[] = [];
        if (systemPrompt) {
          parts.push({ text: `System Instruction: ${systemPrompt}\n\n` });
        }
        parts.push({ text: userPrompt });
        contents.push({ parts });

        const res = await fetch(url, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents,
            generationConfig: {
              temperature,
              maxOutputTokens: maxTokens,
              ...(jsonMode ? { responseMimeType: "application/json" } : {}),
            },
          }),
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData?.error?.message || `Gemini error: ${res.statusText}`);
        }

        const data = await res.json();
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text || "";
        let parsedData: any = undefined;
        if (jsonMode) {
          try {
            parsedData = JSON.parse(text);
          } catch {}
        }

        const promptTokens = data.usageMetadata?.promptTokenCount || Math.ceil(userPrompt.length / 4);
        const completionTokens = data.usageMetadata?.candidatesTokenCount || Math.ceil(text.length / 4);

        return {
          text,
          data: parsedData,
          tokensUsed: {
            promptTokens,
            completionTokens,
            totalTokens: promptTokens + completionTokens,
          },
          durationMs: Date.now() - startTime,
          providerUsed: `Gemini (${model})`,
        };
      }

      case "groq": {
        const apiKey = apiKeys.groq;
        if (!apiKey) throw new Error("Groq API key is missing in Settings");

        const messages: any[] = [];
        if (systemPrompt) {
          messages.push({ role: "system", content: systemPrompt });
        }
        messages.push({ role: "user", content: userPrompt });

        const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model: model || "llama-3.3-70b-versatile",
            messages,
            temperature,
            max_tokens: maxTokens,
            ...(jsonMode ? { response_format: { type: "json_object" } } : {}),
          }),
        });

        if (!res.ok) {
          const errData = await res.json().catch(() => ({}));
          throw new Error(errData?.error?.message || `Groq error: ${res.statusText}`);
        }

        const data = await res.json();
        const text = data.choices?.[0]?.message?.content || "";
        let parsedData: any = undefined;
        if (jsonMode) {
          try {
            parsedData = JSON.parse(text);
          } catch {}
        }

        return {
          text,
          data: parsedData,
          tokensUsed: {
            promptTokens: data.usage?.prompt_tokens || 0,
            completionTokens: data.usage?.completion_tokens || 0,
            totalTokens: data.usage?.total_tokens || 0,
          },
          durationMs: Date.now() - startTime,
          providerUsed: `Groq (${model})`,
        };
      }

      case "ollama": {
        const baseUrl = apiKeys.ollamaUrl || "http://localhost:11434";
        const res = await fetch(`${baseUrl}/api/chat`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            model: model || "llama3.2",
            messages: [
              ...(systemPrompt ? [{ role: "system", content: systemPrompt }] : []),
              { role: "user", content: userPrompt },
            ],
            stream: false,
            options: {
              temperature,
              num_predict: maxTokens,
            },
            ...(jsonMode ? { format: "json" } : {}),
          }),
        });

        if (!res.ok) {
          throw new Error(`Ollama connection error: ${res.statusText}. Make sure Ollama is running at ${baseUrl}`);
        }

        const data = await res.json();
        const text = data.message?.content || "";
        let parsedData: any = undefined;
        if (jsonMode) {
          try {
            parsedData = JSON.parse(text);
          } catch {}
        }

        const promptTokens = data.prompt_eval_count || Math.ceil(userPrompt.length / 4);
        const completionTokens = data.eval_count || Math.ceil(text.length / 4);

        return {
          text,
          data: parsedData,
          tokensUsed: {
            promptTokens,
            completionTokens,
            totalTokens: promptTokens + completionTokens,
          },
          durationMs: Date.now() - startTime,
          providerUsed: `Ollama (${model})`,
        };
      }

      default:
        throw new Error(`Unsupported AI Provider: ${provider}`);
    }
  } catch (error: any) {
    throw new Error(`[${provider}] API Call Failed: ${error.message || error}`);
  }
}
